import type { LeadStatus } from './types';

export const TRANSITIONS: Record<LeadStatus, LeadStatus[]> = {
  NEW: ['IN_SERVICE', 'IN_QUALIFICATION', 'NO_RESPONSE', 'LOST', 'ARCHIVED'],
  AWAITING_DISTRIBUTION: ['IN_SERVICE', 'LOST', 'ARCHIVED'],
  DISTRIBUTED: ['IN_SERVICE', 'NO_RESPONSE', 'LOST', 'ARCHIVED'],
  IN_SERVICE: ['IN_QUALIFICATION', 'NO_RESPONSE', 'VISIT_SUGGESTED', 'VISIT_SCHEDULED', 'FUTURE_PROPOSAL', 'RESOLVED', 'LOST', 'TO_REDISTRIBUTE', 'ARCHIVED'],
  NO_RESPONSE: ['IN_SERVICE', 'IN_QUALIFICATION', 'LOST', 'TO_REDISTRIBUTE', 'ARCHIVED'],
  IN_QUALIFICATION: ['IN_SERVICE', 'VISIT_SUGGESTED', 'VISIT_SCHEDULED', 'FUTURE_PROPOSAL', 'NO_RESPONSE', 'RESOLVED', 'LOST', 'ARCHIVED'],
  VISIT_SUGGESTED: ['VISIT_SCHEDULED', 'IN_QUALIFICATION', 'NO_RESPONSE', 'FUTURE_PROPOSAL', 'RESOLVED', 'LOST', 'ARCHIVED'],
  VISIT_SCHEDULED: ['FUTURE_PROPOSAL', 'IN_QUALIFICATION', 'NO_RESPONSE', 'RESOLVED', 'LOST', 'ARCHIVED'],
  FUTURE_PROPOSAL: ['RESOLVED', 'IN_QUALIFICATION', 'NO_RESPONSE', 'LOST', 'ARCHIVED'],
  RESOLVED: ['ARCHIVED'],
  LOST: ['IN_SERVICE', 'ARCHIVED'],
  TO_REDISTRIBUTE: ['IN_SERVICE', 'LOST', 'ARCHIVED'],
  ARCHIVED: [],
};
export const REASON_REQUIRED: LeadStatus[] = ['LOST', 'ARCHIVED'];
export const allowedTransitions = (s: LeadStatus) => TRANSITIONS[s] ?? [];
export const reasonRequired = (s: LeadStatus) => REASON_REQUIRED.includes(s);
